// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionWorkflowEngine.Data;

#nullable disable

namespace TransactionWorkflowEngine.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionWorkflowEngine.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionHistories");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransactionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 932, DateTimeKind.Utc).AddTicks(8673),
                            Description = "Transaction has been created",
                            DisplayOrder = 1,
                            IsFinal = false,
                            IsInitial = true,
                            Name = "Created"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 932, DateTimeKind.Utc).AddTicks(9886),
                            Description = "Transaction has been validated",
                            DisplayOrder = 2,
                            IsFinal = false,
                            IsInitial = false,
                            Name = "Validated"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 932, DateTimeKind.Utc).AddTicks(9889),
                            Description = "Transaction is being processed",
                            DisplayOrder = 3,
                            IsFinal = false,
                            IsInitial = false,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 932, DateTimeKind.Utc).AddTicks(9891),
                            Description = "Transaction has been completed",
                            DisplayOrder = 4,
                            IsFinal = true,
                            IsInitial = false,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 932, DateTimeKind.Utc).AddTicks(9893),
                            Description = "Transaction processing failed",
                            DisplayOrder = 5,
                            IsFinal = false,
                            IsInitial = false,
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionStatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRollback")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresComment")
                        .HasColumnType("bit");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("FromStatusId", "ToStatusId")
                        .IsUnique();

                    b.ToTable("TransactionStatusTransitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 933, DateTimeKind.Utc).AddTicks(5028),
                            Description = "Validate the created transaction",
                            FromStatusId = 1,
                            IsRollback = false,
                            Name = "Validate",
                            RequiresComment = false,
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 933, DateTimeKind.Utc).AddTicks(5961),
                            Description = "Begin processing the validated transaction",
                            FromStatusId = 2,
                            IsRollback = false,
                            Name = "Start Processing",
                            RequiresComment = false,
                            ToStatusId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 933, DateTimeKind.Utc).AddTicks(5964),
                            Description = "Mark transaction as completed",
                            FromStatusId = 3,
                            IsRollback = false,
                            Name = "Complete",
                            RequiresComment = false,
                            ToStatusId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 933, DateTimeKind.Utc).AddTicks(5965),
                            Description = "Mark transaction as failed",
                            FromStatusId = 3,
                            IsRollback = false,
                            Name = "Fail",
                            RequiresComment = true,
                            ToStatusId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 12, 10, 20, 27, 933, DateTimeKind.Utc).AddTicks(6118),
                            Description = "Retry the failed transaction",
                            FromStatusId = 5,
                            IsRollback = true,
                            Name = "Retry",
                            RequiresComment = false,
                            ToStatusId = 2
                        });
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.Transaction", b =>
                {
                    b.HasOne("TransactionWorkflowEngine.Models.TransactionStatus", "Status")
                        .WithMany("Transactions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionHistory", b =>
                {
                    b.HasOne("TransactionWorkflowEngine.Models.TransactionStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransactionWorkflowEngine.Models.TransactionStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransactionWorkflowEngine.Models.Transaction", "Transaction")
                        .WithMany("History")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionStatusTransition", b =>
                {
                    b.HasOne("TransactionWorkflowEngine.Models.TransactionStatus", "FromStatus")
                        .WithMany("TransitionsFrom")
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransactionWorkflowEngine.Models.TransactionStatus", "ToStatus")
                        .WithMany("TransitionsTo")
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.Transaction", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("TransactionWorkflowEngine.Models.TransactionStatus", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("TransitionsFrom");

                    b.Navigation("TransitionsTo");
                });
#pragma warning restore 612, 618
        }
    }
}
